name: pipeline-repair-env
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - ncurses=6.2
  - openssl=1.1.1e
  - pip=20.0.2=py37_1
  - python=3.7.6
  - readline=7.0
  - setuptools=46.0.0=py37_0
  - sqlite=3.31.1
  - wheel=0.34.2=py37_0
  - zlib=1.2.11
  - pip:
    - appnope==0.1.0
    - backcall==0.1.0
    - bs4==4.9.3
    - chardet==3.0.4
    - cycler==0.10.0
    - deap==1.3.1
    - decorator==4.4.2
    - graphviz==0.15
    - idna==2.9
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - jedi==0.16.0
    - joblib==0.14.1
    - kaggle==1.5.8
    - kiwisolver==1.1.0
    - matplotlib==3.2.1
    - nbconvert==6.0.7
    - numpy==1.18.2
    - openml==0.10.2
    - pandas==1.0.3
    - parso==0.6.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pmlb==1.0
    - prompt-toolkit==3.0.4
    - ptyprocess==0.6.0
    - pygments==2.6.1
    - pyparsing==2.4.6
    - pytest==5.4.2
    - python-dateutil==2.8.1
    - pytz==2019.3
    - requests==2.23.0
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - seaborn==0.11.0
    - six==1.14.0
    - stopit==1.1.2
    - statsmodels==0.12.0
    - tqdm==4.43.0
    - traitlets==4.3.3
    - update-checker==0.16
    - urllib3==1.25.8
    - wcwidth==0.1.8
    - xgboost==1.0.2
    - zss==1.2.0
